# Generated by Django 3.2.8 on 2021-10-22 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=127, verbose_name='Имя учителя')),
                ('last_name', models.CharField(max_length=127, null=True, verbose_name='Фамилия учителя')),
                ('patronymic', models.CharField(max_length=127, null=True, verbose_name='Отчество учителя')),
                ('about', models.TextField(verbose_name='О преподователе')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/mainapp/images', verbose_name='Фото учителя')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=127, verbose_name='Название предмета')),
                ('duration', models.PositiveIntegerField(default=0)),
                ('about', models.TextField()),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.teacher', verbose_name='Учитель курса')),
            ],
        ),
    ]
