# Generated by Django 3.2.8 on 2022-02-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_courserequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserequest',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
